---
- hosts: sensu_masters
  pre_tasks:
  - name: Make sure the correct version of Erlang is used
    copy:
      dest: "/etc/apt/preferences.d/erlang"
      content: |
          Package: esl-erlang erlang*
          Pin: version 1:20*
          Pin-Priority: 999
    become: yes
  roles:
    - role: sensu-ansible
      sensu_master: true
      sensu_include_dashboard: true
      rabbitmq_server: true
      redis_server: true
      sensu_pushover_userkey: u5x5p1diu43n8oreodo1gru7yvooaf
      sensu_pushover_token: a6rhg4a3wngrc35g1fj1wij137dd32
      sensu_client_subscriptions:
        - production
      become: yes
  tasks:
  - name: Install Graphite plugin
    gem: 
      name: sensu-plugins-graphite 
      version: 3.1.0
      state: present 
      executable: /opt/sensu/embedded/bin/gem

- hosts: all:!sensu_masters
  roles:
    - role: sensu-ansible
      sensu_client_subscriptions:
        - production
        - workstation
      become: yes

- hosts: graphite_masters
  tasks:
  - name: Deploy graphite container
    docker_container:
      name: graphite
      image: graphiteapp/graphite-statsd
      restart_policy: always
      ports:
        - "8088:80"
        - "2003:2003"
        - "2004:2004"
        - "2023:2023"
        - "2024:2024"
        - "8125:8125/udp"
        - "8126:8126"